version: '3.7'

services:
  app:
    build: ..
    #    working_dir: /var/www
    #    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    ports:
      - 8080:80
    volumes:
      - ../var:/var/www/var
#      - logs:/var/www/logs

volumes:
  logs:
    driver: local
